name: save-to-scsm
run-name: ${{ github.actor }} is doing some stuff
on: [push]
jobs:
  update-sm-code:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: get changed files
        id: changed-files
        uses: tj-actions/changed-files@v32
      - name: Script
        run: ./merge.ps1
        shell: powershell.exe