name: save-to-scsm
run-name: ${{ github.actor }} is doing some stuff
on: [push]
jobs:
  update-sm-code:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: get changed files
        id: changed-files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - name: Script
        run: ./merge.ps1
        shell: powershell.exe
        env:
          FilesOutput: ${{steps.changed-files.outputs.All}}